name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: '.node-version'
          cache: pnpm
      - name: Install dependencies
        shell: bash
        run: |
          corepack enable
          pnpm install
      - name: Run lint
        run: pnpm lint
